#!/usr/local/bin/fish

set FUNC rekog-poc-detect
set PROFILE aklambda

rm one.zip
zip -r one.zip index.js node_modules package.json

aws lambda update-function-code --region us-west-2 --profile $PROFILE --function-name $FUNC --zip-file fileb://one.zip
#aws lambda create-function --region us-west-2 --runtime nodejs4.3 --role arn:aws:iam::268578439486:role/service-role/slackGoogleRole --profile $PROFILE --function-name $FUNC --handler index.handler --timeout 10 --zip-file fileb://one.zip
